prrint ("Hello wereld van…")                                    
print ('pppp    y     y   ttttttt   h   h    oooo   nnnn")         
print ("p   p    y   y       t      h   h   o    o  n   n")
print ("p   p     y y        t      h   h   o    o  n   n")
print ("p          y         t      h   h   o    o  n   n")
print ("p          y         t      h   h    oooo   n   n")
prinnct ("# Ali Goutsal")
print ("# 99050199")